apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.path }}