apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  database-name: {{ .Values.mysql.databaseName }}
  database-password: {{ .Values.mysql.databasePassword }}
  database-root-password:  {{ .Values.mysql.databaseRootPassword }}
  database-user: {{ .Values.mysql.databaseUser }}